### ISSUE TITLE
How to use the pre-trained model?

### ISSUE THREAD

**Issue by ypflll** [MG2033/MobileNet#1]
A little new to tf.
I get mobilenet_v1.pkl follow the link you give and load it with pickle.load, then I get a dict with 137 keys.
But how to restore the model form this dict?

Actually, I have implement a net follow this: https://arxiv.org/pdf/1712.07168.pdf.
In this paper, only part of the mobilenet is used as the encoder part. In this case, the pre-trained model can be used?

**Comment by MG2033** [comment]
For the first question, you don't need to write any code to load the model from this dictionary. It gets loaded automatically using load_model() in train.py.
As for the second question, yes it can be used if you use the function above with the same name scopes for the encoder. Otherwise, you have to convert the dictionary names to the new name scopes.

**Comment by ypflll** [comment]
I have implemented my app refer to your code.
Thank for your help^_^
